language: php

node_js:
  - '8'

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install
#  - export typo3DatabaseName="typo3"
#  - export typo3DatabaseHost="localhost"
#  - export typo3DatabaseUsername="root"
#  - export typo3DatabasePassword=""

script:
  - ./bin/phpunit
