version: '2'

services:
  web:
    build: docker/httpd
    volumes:
      - .:/app
      - ./docker/httpd/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
  php:
    build: docker/php-fpm
    volumes:
      - .:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    working_dir: /app
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - BLACKFIRE_CLIENT_TOKEN
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_LOG_LEVEL=4
      - COMPOSER_HOME=/app/docker/composer
      - LOCAL_USER_ID
      - TYPO3_COMPOSER_AUTOLOAD=On
    networks:
      - backend
  db:
    build: docker/mysql
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: tox_typo3
#      MYSQL_PASSWORD: pass
    networks:
      - backend

networks:
  backend: ~
