version: '2'

services:
  web:
    build: docker/httpd
    image: tox-t3/httpd:2.4.25
    volumes:
      - .:/app
      - ./docker/httpd/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./docker/httpd/ssl:/usr/local/apache2/ssl
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
  php:
    build: docker/php-fpm
    image: tox-t3/php-fpm:5.6.31
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN
      - BLACKFIRE_CLIENT_TOKEN
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_LOG_LEVEL=4
      - COMPOSER_HOME=/app/docker/composer
      - LOCAL_USER_ID
      - TYPO3_COMPOSER_AUTOLOAD=On
      # next setting for php-dev only
      - PHP_IDE_CONFIG=serverName=tox-typo3.local
      - TYPO3_CONTEXT=Development
#      - XDEBUG_CONFIG=remote_host=192.168.130.106 idekey=xdebug
    networks:
      - backend
  db:
    build: docker/mysql
    image: tox-t3/mysql:5.7.17
    volumes:
      - .:/app
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: tox_typo3
#      MYSQL_PASSWORD: pass
    networks:
      - backend

networks:
  backend: ~
