version: '2'

services:
  web:
    build: docker/httpd
    volumes:
      - .:/app
      - ./docker/httpd/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
  php:
    image: php:7.1.2-fpm-alpine
    volumes:
      - .:/app
    working_dir: /app
#    links:
#      - db
#  db:
#    image: mariadb:latest
#    ports:
#      - "3306:3306"
#    volumes:
#      - /private/var/lib/mysql:/var/lib/mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpass
#      MYSQL_DATABASE: db
#      MYSQL_USER: user
#      MYSQL_PASSWORD: pass
